homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('gallery/', views.gallery, name='gallery'),
    path('form/', views.tampil , name='form'),
    path('buat/', views.create_jadwal, name='buat'),
    path('<int:query_id>', views.delete, name='value')
    # dilanjutkan ...
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=100)
    tempat = models.CharField(max_length=50)
    kategori = models.CharField(null=True, max_length=25)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.nama_kegiatan

homepage/forms.py
from django import forms
import datetime
from .models import Jadwal

class JadwalForm(forms.ModelForm):
    nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
            "class" : "form-control",
            "required" : True,
            "placeholder":"Activity",
            }), label ="Nama Kegiatan")
    tempat = forms.CharField(widget=forms.TextInput(attrs={
            "class" : "form-control",
            "required" : True,
            "placeholder":"Place",
            }), label ="Place")
    kategori = forms.CharField(widget=forms.TextInput(attrs={
            "class" : "form-control",
            "required" : True,
            "placeholder":"Category",
            }), label ="Category")
    tanggal = forms.DateField(widget=forms.DateInput(attrs={
            "class" : "form-control",
            "required" : True,
            'placeholder':'Select a date',
            'type':'date',
            }), label ="Date")
    waktu = forms.TimeField(widget=forms.TimeInput(attrs={
            "class" : "form-control",
            "placeholder":"hh:mm",
            "required" : True,
            "type" : 'time',
            }), label ="Time") 

    class Meta:
        model = Jadwal
        fields = [
            'nama_kegiatan',
            'kategori',
            'tempat',
            'tanggal',
            'waktu',
        ]

homepage/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Jadwal
from .forms import JadwalForm
import datetime
from django.utils import timezone



# Create your views here.
def landing(request):
    return render(request, 'index.html')

def gallery(request):
    return render(request, 'gallery.html')

def tampil(request):
    form = JadwalForm()
    kegiatan = Jadwal.objects.all()
    context = {
        'item' : kegiatan,
        'form' : form
    }
    return render(request, 'form.html', context)

def create_jadwal(request):
    form = JadwalForm(request.POST)
    if form.is_valid():
        form.save()

    return redirect('homepage:form')

def delete(request, query_id):
    Jadwal.objects.filter(id=query_id).delete()
    return redirect('homepage:form')

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Profile Pow</title>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'images/p-type_logo_instagram.png' %}" >
</head>

{% block body %}
{% endblock %}

</html>

homepage/templates/form.html
{% extends 'base.html' %}

{% block body %}
<body style="background: linear-gradient(90deg, rgba(255, 203, 168, 0.3) 0%, rgba(255, 255, 255, 0.3) 100%), #FFC5A1; font-family: 'Montserrat', sans-serif;">
    <div class="p-4">
        <div>
            <h1 class="logo2 text-center"><a href="{% url 'homepage:landing' %}">MY &nbsp; SCHEDULE</a></h1>
        </div>
        <div class="container pt-4">
            <form action="{% url 'homepage:buat' %}" method="POST" style="font-size: 25px; font-weight:450;"> {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-info mt-2">Save</button>
            </form>
        </div>
        <div class="container pt-4">
            {% for items in item %}
                <div class="card p-3 m-3">
                    <h1>{{ items }}</h1>
                    <h2>{{ items.kategori }}</h2>
                    <h2>{{ items.tempat }}</h2>
                    <h2>{{ items.tanggal }}</h2>
                    <h2>{{ items.waktu }}</h2>
                    <form method="POST" action="{% url 'homepage:value' items.id%}"> {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
                
            {% endfor %}
        </div>
    </div>
</body>


{% endblock body %}

homepage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Gallery Pow</title>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/gallery_style.css' %}" >
    <link rel="icon" type="image/ico" href="{% static 'images/p-type_logo_instagram.png' %}" />
</head>
<body id="bodygallery">
    <div class="landing">
        <div class="title">
            <h1 class="logo"><a href="{% url 'homepage:landing' %}">LA POW GALLERIA</a></h1>
        </div>
    </div>
    <div class="gallery">
        <div class="row">
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Birds1.JPG' %}" target="_blank">
                    <img src="{% static 'images/Birds1.JPG' %}" alt="Lake Bird" style="width:100%">
                    <div class="caption">
                    <p>"By The Lake"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Birds2.JPG' %}" target="_blank">
                    <img src="{% static 'images/Birds2.JPG' %}" alt="scratch" style="width:100%">
                    <div class="caption">
                    <p>"Feather Bites"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Birds3.JPG' %}" target="_blank">
                    <img src="{% static 'images/Birds3.JPG' %}" alt="bridge" style="width:100%">
                    <div class="caption">
                    <p>"Oil Near The Bridge"</p>
                    </div>
                </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Boat1.JPG' %}" target="_blank">
                    <img src="{% static 'images/Boat1.JPG' %}" alt="delia" style="width:100%">
                    <div class="caption">
                    <p>"Delia and Him"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Boat2.JPG' %}" target="_blank">
                    <img src="{% static 'images/Boat2.JPG' %}" alt="queen" style="width:100%">
                    <div class="caption">
                    <p>"The Queen of The Lake"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Boat3.JPG' %}" target="_blank">
                    <img src="{% static 'images/Boat3.JPG' %}" alt="melanie" style="width:100%">
                    <div class="caption">
                    <p>"Melanie"</p>
                    </div>
                </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Car1.JPG' %}" target="_blank">
                    <img src="{% static 'images/Car1.JPG' %}" alt="Headlight" style="width:100%">
                    <div class="caption">
                    <p>"Headlight"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Car2.JPG' %}" target="_blank">
                    <img src="{% static 'images/Car2.JPG' %}" alt="austin7" style="width:100%">
                    <div class="caption">
                    <p>"Austin 7"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/Car3.JPG' %}" target="_blank">
                    <img src="{% static 'images/Car3.JPG' %}" alt="road" style="width:100%">
                    <div class="caption">
                    <p>"By The Road"</p>
                    </div>
                </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/animal1.JPG' %}" target="_blank">
                    <img src="{% static 'images/animal1.JPG' %}" alt="chipmunk" style="width:100%">
                    <div class="caption">
                    <p>"Surprised Chipmunk"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/animal2.JPG' %}" target="_blank">
                    <img src="{% static 'images/animal2.JPG' %}" alt="swan" style="width:100%">
                    <div class="caption">
                    <p>"Great White Swan"</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail kotak">
                <a href="{% static 'images/animal3.JPG' %}" target="_blank">
                    <img src="{% static 'images/animal3.JPG' %}" alt="sheeps" style="width:100%">
                    <div class="caption">
                    <p>"Mountain Sheep"</p>
                    </div>
                </a>
                </div>
            </div>
        </div>
    </div>
</body>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Profile Pow</title>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'images/p-type_logo_instagram.png' %}" >
</head>
<body>
    <div class="home" id="landing_page">
        <div class="miring">
            <div class="content">
                <div>
                    <h1 class="logo"><a href="{% url 'homepage:gallery' %}">POW</a></h1>
                    <nav class="navbar">
                        <ul class="navbtn">
                            <li><p><a href="#about_page" >About </a></p></li>
                            <li>/</li>
                            <li><p><a href="#experience_page" >Experience </a></p></li>
                            <li>/</li>
                            <li><p><a href="#skills_page" >Skills </a></p></li>
                            <li>/</li>
                            <li><p><a href="{% url 'homepage:form' %}" >Schedule</a></p></li>
                            <li>/</li>
                            <li><p><a href="#contact_page" >Contact</a></p></li>
                            <li>/</li>
                        </ul>
                    </nav>
                </div>
                <div>
                    <h1 class="nama">Fachri Anandito</h1>
                    <h2 class="intro">A technology enthusiast who thrive to achieve goals in life.</h2>
                    <div class="readbox" onclick="location.href='#about_page';">
                        <p id="readmore">Read More</p>
                    </div>
                    <img class="ganteng" src="{% static 'images/Group 2.png' %}">
                </div>
            </div>
        </div>
    </div>
    <div class="division" id="about_page">
        <div class="row">
            <div class="col-6">
                <div class="box1">
                    <div class="divtext">
                        <p>ABOUT</p>
                    </div>
                    <nav class="navbar2">
                        <ul class="navbtn">
                            <li><p><a href="#landing_page" >Home </a></p></li>
                            <li>/</li>
                            <li><p><a href="#experience_page" >Experience </a></p></li>
                            <li>/</li>
                            <li><p><a href="#skills_page" >Skills </a></p></li>
                            <li>/</li>
                            <li><p><a href="{% url 'homepage:form' %}" >Schedule</a></p></li>
                            <li>/</li>
                            <li><p><a href="#contact_page" >Contact</a></p></li>
                            <li>/</li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-6">
                <div class="isidiv">
                    <p class="tulisanjudul">I am an Information System undergraduate at the University of Indonesia</p>
                    <p class="tulisanaja">I was born in the big city of Jakarta and lives in Tebet until now. 
                        I currently am taking a major in Information System at the University of Indonesia. 
                        I like to listen to music almost all the time because it is my way to cope with either a bad or good situation. 
                        I am hoping that one day I will be able to inspire a lot of people to be more creative for the sake of 
                        Indonesia Technology Advancement.</p>
                    <p class="tulisanjudul">How technology has affected me</p>
                    <p class="tulisanaja">In this so called the "Hyperconnected" era, technology has been such a big part of our life. Our
                        friends and family are just one tap of a button away from your phone. You can speak to your smartphone or
                        any of your smart gadgets as you were talking to a human. Furthermore, you can even pay your orders by just scanning
                        a random generated barcode </p>
                    <p class="tulisanaja">These are some of the reasons that i decided to continue my study in the field of Information 
                        System at the University of Indonesia. I like to learn things that are related to technology, for example web 
                        developing and programming foundations. I hope all the things that i learn from my study will be useful for my future 
                        occupation. And i hope someday i can be a great leader who can inspire people to create more innovation in the tech industry.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="division" id="experience_page">
        <div class="row">
            <div class="col-6">
                <div class="isidiv">
                    <div class="row">
                        <div class="col-6">
                            <p class="tulisanjudul judulexp">Education</p>
                            <ul class="tulisanaja">
                                <li class="expkind">University of Indonesia</li>
                                <p>(2018 - Now)<br>Undergraduate in the major of Information System</p>
                                <li class="expkind">SMAN 8 Jakarta</li>
                                <p>(2015-2018)</p>
                                <li class="expkind">SMPN 73 Jakarta</li>
                                <p>(2012-2015)</p>
                                <li class="expkind">SDN 19 Pagi Jakarta</li>
                                <p>(2006-2012)</p>
                            </ul>
                        </div>
                        <div class="col-6">
                            <p class="tulisanjudul judulexp">Activities</p>
                            <ul class="tulisanaja">
                                    <li class="expkind">COMPFEST</li>
                                    <p>(2019 - Now)<br>Staff of Seminar</p>
                                    <li class="expkind">OH Fasilkom UI</li>
                                    <p>(2019 - Now)<br>Staff of Liaison Officer</p>
                                    <li class="expkind">BEM Fasilkom UI</li>
                                    <p>(2018 - Now)<br>Staff of Human Resources</p>
                                    <li class="expkind">CGT Fasilkom UI</li>
                                    <p>(2018 - 2019)<br>Staff of Event Division</p>
                                    <li class="expkind">The 7th UI Art War</li>
                                    <p>(2018 - Now)<br>Staff of Grand Opening and Grand Closing</p>
                                    <li class="expkind">T8chnofest 2017</li>
                                    <p>(2018 - Now)<br>Project Officer</p>
                                </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="box2">
                    <div class="divtext">
                        <p>EXPERIENCE</p>
                    </div>
                    <nav class="navbar2">
                        <ul class="navbtn2">
                            <li><p><a href="#landing_page" >Home </a></p></li>
                            <li>/</li>
                            <li><p><a href="#about_page" >About </a></p></li>
                            <li>/</li>
                            <li><p><a href="#skills_page" >Skills </a></p></li>
                            <li>/</li>
                            <li><p><a href="{% url 'homepage:form' %}" >Schedule</a></p></li>
                            <li>/</li>
                            <li><p><a href="#contact_page" >Contact</a></p></li>
                            <li>/</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="division" id="skills_page">
        <div class="row">
            <div class="col-6">
                <div class="box3">
                    <div class="divtext">
                        <p>SKILLS</p>
                    </div>
                    <nav class="navbar2">
                        <ul class="navbtn2">
                            <li><p><a href="#landing_page" >Home </a></p></li>
                            <li>/</li>
                            <li><p><a href="#about_page" >About </a></p></li>
                            <li>/</li>
                            <li><p><a href="#experience_page" >Experience </a></p></li>
                            <li>/</li>
                            <li><p><a href="{% url 'homepage:form' %}" >Schedule</a></p></li>
                            <li>/</li>
                            <li><p><a href="#contact_page" >Contact</a></p></li>
                            <li>/</li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-6">
                <div class="isidiv">
                    <p class="text_skills">Python</p>
                    <div class="skills_container">
                        <div class="skills python warnaskill">85%</div>
                    </div>
                    
                    <p class="text_skills">Java</p>
                    <div class="skills_container">
                        <div class="skills java">75%</div>
                    </div>
                    
                    <p class="text_skills">HTML & CSS</p>
                    <div class="skills_container">
                        <div class="skills htmlcss">60%</div>
                    </div>
                    
                    <p class="text_skills">Figma</p>
                    <div class="skills_container">
                        <div class="skills figma">60%</div>
                    </div>

                    <p class="text_skills">UI/UX</p>
                    <div class="skills_container">
                        <div class="skills uiux">45%</div>
                    </div>

                    <p class="text_skills">Public Speaking</p>
                    <div class="skills_container">
                        <div class="skills publicspeaking">70%</div>
                    </div>

                    <p class="text_skills">Leadership</p>
                    <div class="skills_container">
                        <div class="skills leadership">75%</div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="division" id="contact_page">
        <div class="row">
            <div class="col-12">
                <div class="bg_contact">
                    <div class="contact_icon">
                        <a href="https://twitter.com/mfaaaach" target="_blank"><img src="{% static 'images/icons/3x/Asset 5@3x.png' %}"></a>
                        <a href="https://instagram.com/mfaaach" target="_blank"><img src="{% static 'images/icons/3x/Asset 4@3x.png' %}"></a>
                        <a href="https://www.linkedin.com/in/muhammad-fachri-a-993a75114/" target="_blank"><img src="{% static 'images/icons/3x/Asset 3@3x.png' %}"></a>
                        <a href="https://www.youtube.com/watch?v=ZEssTprd2Hs" target="_blank"><img src="{% static 'images/icons/3x/Asset 2@3x.png' %}"></a>
                        <a href="https://www.facebook.com/mfaaach" target="_blank"><img src="{% static 'images/icons/3x/Asset 1@3x.png' %}"></a>
                    </div>
                    <div class="contact_text">
                        <p>CONTACT ME</p>
                    </div>
                    <nav class="navbar3">
                        <ul class="navbtn2">
                            <li><p><a href="#landing_page" >Home </a></p></li>
                            <li>/</li>
                            <li><p><a href="#about_page" >About </a></p></li>
                            <li>/</li>
                            <li><p><a href="#experience_page" >Experience </a></p></li>
                            <li>/</li>
                            <li><p><a href="#skills_page" >Skills</a></p></li>
                            <li>/</li>
                            <li><p><a href="{% url 'homepage:form' %}" >Schedule</a></p></li>
                            <li>/</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</body>
    
</html>